// Hotel API

GET {{url}}/hotels
Authorization: Bearer {{token}}

###

GET {{url}}/hotels/1
Authorization: Bearer {{token}}

###

POST {{url}}/hotels
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "hotelName": "Radisson",
  "hotelAddress": "Sindelfingen",
  "hotelType": "BUDGET"
}

###

PUT {{url}}/hotels/2
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "hotelName": "Scandic",
  "hotelAddress": "Lyngby Hovedgade",
  "hotelType": "BUDGET"
}

###

DELETE {{url}}/hotels/540
Authorization: Bearer {{token}}

###
